#!/bin/bash

# Install XDS tools and setup initial home
# directory structure.

# 'DISTRO' can be set to { xUbuntu_16.04, xUbuntu_16.10, xUbuntu_17.04, Debian_8.0, Debian_9.0 }
export DISTRO="Debian_9.0"

wget -O - http://download.opensuse.org/repositories/isv:/LinuxAutomotive:/app-Development/${DISTRO}/Release.key | sudo apt-key add -
sudo bash -c "cat >> /etc/apt/sources.list.d/AGL.list <<EOF
deb http://download.opensuse.org/repositories/isv:/LinuxAutomotive:/app-Development/${DISTRO}/ ./
EOF"

apt-get update -y
apt-get upgrade -y
apt-get install -y agl-xds-agent agl-xds-cli agl-xds-gdb

# jenkins user lingering service to be sure that jenkins user session is running
# and consequently xds-server is running as a user systemd service
mkdir -p /lib/systemd/system/ /lib/systemd/system/multi-user.target.wants/
cat <<EOF >/lib/systemd/system/autologin.service
[Unit]
Description=Auto user lingering service for jenkins user
After=network.target

[Service]
ExecStart=-/bin/loginctl enable-linger slzave

RemainAfterExit=yes
[Install]
WantedBy=multi-user.target
EOF
ln -s ../autologin.service /lib/systemd/system/multi-user.target.wants/

systemctl enable autologin.service
systemctl --user enable xds-agent.service

sudo sed -i s/"localhost:8000"/"172.42.0.3:8000"/g /etc/xds/agent/agent-config.json