#!/bin/bash

# add some cool base tools
apt-get install -y man tree curl screen 

# add the build user
useradd -c "Builder" -d $AGENTUSER_HOME -G sudo -m -U -s /bin/bash -u $AGENTUSER_UID $AGENTUSER
echo $AGENTUSER:$AGENTUSER_PASSWORD | chpasswd 

# generate an extra environment file sourced by bashrc
for k in	AGENTUSER AGENTUSER_UID AGENTUSER_HOME \
			XDT_DIR \
			XDT_META XDT_DOWNLOADCACHE XDT_SSTATECACHE XDT_CCACHE XDT_BUILD XDT_WORKSPACE XDT_SOURCES XDT_SDK \
			; do
	v=${!k} # get value
	[[ "${v:0:1}" == "/" ]] && mkdir -p $v # create dir only if value starts with "/"
	echo "export $k=$v" >>/etc/xdtrc
done

mkdir -p $AGENTUSER_HOME/bin
cat <<'EOF' >>$AGENTUSER_HOME/.bashrc

# added by worker image creation script (docker-image-builder)
export PATH=~/bin:$PATH
[[ -f /etc/xdtrc ]] && . /etc/xdtrc

EOF

chown -R $AGENTUSER:$AGENTUSER $XDT_DIR
chown -R $AGENTUSER:$AGENTUSER $AGENTUSER_HOME

